//! Tests for the self-contained HTML report.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod common;

use plexuspact_report::render_html;

#[test]
fn html_mixed_failures_golden() {
    let out = render_html(&common::mixed_failures()).unwrap();
    insta::assert_snapshot!("html_mixed_failures", out);
}

#[test]
fn html_is_self_contained_no_external_requests() {
    // The fixtures contain no URLs in user data, so ANY scheme substring in
    // the output would mean the template itself references an external
    // resource — which is forbidden (doc 03 §2: single self-contained file).
    for result in [
        common::all_pass(),
        common::mixed_failures(),
        common::empty_dataset(),
        common::huge_numbers(),
    ] {
        let out = render_html(&result).unwrap();
        assert!(
            !out.contains("http://"),
            "HTML must not reference http:// resources"
        );
        assert!(
            !out.contains("https://"),
            "HTML must not reference https:// resources"
        );
        assert!(!out.contains("<script"), "HTML must not require JavaScript");
    }
}

#[test]
fn html_escapes_user_data() {
    let mut result = common::mixed_failures();
    result.checks[3].samples[0].value = "<script>alert('x')</script>".to_owned();
    result.checks[3].message = Some("bad & <b>bold</b>".to_owned());
    let out = render_html(&result).unwrap();
    assert!(
        !out.contains("<script>alert"),
        "sample values must be HTML-escaped"
    );
    assert!(out.contains("&lt;script&gt;"));
    assert!(out.contains("bad &amp; &lt;b&gt;bold&lt;&#x2F;b&gt;"));
}

#[test]
fn html_carries_run_metadata_and_summary() {
    let out = render_html(&common::mixed_failures()).unwrap();
    assert!(out.contains("user_signups"));
    assert!(out.contains("FAILED"));
    assert!(out.contains("abababababab"), "short contract sha");
    assert!(out.contains("0.1.0"), "tool version");
    assert!(out.contains("2026-07-09 10:11:12 UTC"));
    assert!(out.contains("1,204,441"));
    assert!(out.contains("6.2s"));
    assert!(out.contains("812.3 MB"));
    // Observed metrics render when non-empty.
    assert!(out.contains("newest_age_hours"));
    // Footer.
    assert!(out.contains("generated by plexuspact"));
}
